parameters:
    graviton.cache.listener.etagresponselistener.class: Graviton\CacheBundle\Listener\ETagResponseListener
    graviton.cache.listener.ifnonematchresponselistener.class: Graviton\CacheBundle\Listener\IfNoneMatchResponseListener
    graviton.cache.listener.varnish.class: Graviton\CacheBundle\Listener\VarnishListener
