services:
    graviton.cache.listener.etagresponselistener:
        class: "%graviton.cache.listener.etagresponselistener.class%"
        tags:
          -
            name: kernel.event_listener
            event: kernel.response
            method: onKernelResponse
            priority: 110

    graviton.cache.listener.ifnonematchresponselistener:
        class: "%graviton.cache.listener.ifnonematchresponselistener.class%"
        tags:
          -
            name: kernel.event_listener
            event: kernel.response
            method: onKernelResponse
            priority: 100

    graviton.cache.listener.varnish:
      class: '%graviton.cache.listener.varnish.class%'
      tags:
        - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
      arguments:
        - "@logger"
        - "%graviton.cache.server.hostname%"
        - "%graviton.cache.server.header%"

    Graviton\CacheBundle\Factory\CacheFactory:
      arguments:
        - "@cache.app"
        - "%graviton.cache.redis.host%"
        - "%graviton.cache.redis.port%"

    graviton.cache.adapter.app:
      class: Symfony\Component\Cache\Adapter\AdapterInterface
      factory: ['@Graviton\CacheBundle\Factory\CacheFactory', 'getInstance']
      arguments: [true]

    ## public aliases for doctrine cache bundle providers
    graviton.cache.provider.local:
        alias: doctrine_cache.providers.local
        public: true
    graviton.cache.provider.file:
        alias: doctrine_cache.providers.file
        public: true
    graviton.cache.provider.array:
        alias: doctrine_cache.providers.array
        public: true
    graviton.cache.provider.redis:
        alias: doctrine_cache.providers.redis
        public: true
