services:
    graviton.cache.listener.etagresponselistener:
        class: "%graviton.cache.listener.etagresponselistener.class%"
        tags:
          -
            name: kernel.event_listener
            event: kernel.response
            method: onKernelResponse
            priority: 110

    graviton.cache.listener.ifnonematchresponselistener:
        class: "%graviton.cache.listener.ifnonematchresponselistener.class%"
        tags:
          -
            name: kernel.event_listener
            event: kernel.response
            method: onKernelResponse
            priority: 100

    graviton.cache.listener.varnish:
      class: '%graviton.cache.listener.varnish.class%'
      tags:
        - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
      calls:
        - method: setLogger
          arguments:
            - '@logger'
        - method: setResponseTagger
          arguments:
            - '@fos_http_cache.http.symfony_response_tagger'
        - method: setCacheManager
          arguments:
            - '@fos_http_cache.cache_manager'

    ## public aliases for doctrine cache bundle providers
    graviton.cache.provider.local:
        alias: doctrine_cache.providers.local
        public: true
    graviton.cache.provider.file:
        alias: doctrine_cache.providers.file
        public: true
    graviton.cache.provider.array:
        alias: doctrine_cache.providers.array
        public: true
    graviton.cache.provider.redis:
        alias: doctrine_cache.providers.redis
        public: true
