# action.yml
name: 'Graviton test php 7.4'
description: 'tests'
inputs:
  github-token:
    description: 'Github token'
    required: false
    default: 'no'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
