filter:
    excluded_paths:
        - 'vendor/*'
        - 'app/*'
        - 'web/*'
before_commands:
    - 'composer install --dev'
tools:
    external_code_coverage: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    php_code_sniffer:
        config:
    php_sim: true
    php_cpd: false
