language: php
services: 
- mongodb
- rabbitmq
sudo: false
before_script:
- if [ $(phpenv version-name) != "hhvm" ] && [ $(phpenv version-name) != "7.0" ]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
- if [ $(phpenv version-name) = "hhvm" ] || [ $(phpenv version-name) = "7.0" ]; then composer require mongofill/mongofill --ignore-platform-reqs; fi
- composer install --no-interaction  --ignore-platform-reqs
- touch src/Graviton/I18nBundle/Resources/translations/i18n.de.odm
- touch src/Graviton/I18nBundle/Resources/translations/i18n.es.odm
- wget https://scrutinizer-ci.com/ocular.phar
php:
- hhvm
- 5.6
- 5.5
- 5.4
- 7.0
matrix:
  allow_failures:
  - php: hhvm
  - php: 5.4
  - php: 7.0
script:
- "./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover"
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
- composer check
notifications:
  hipchat:
    rooms:
      secure: F5pTVtwBACRIXMdkQ/oE6f5faK3eHvPqDmD7jmAv4vU7Nyog4RN1h1nqa8kJo6fRaRvdbIF5ovAwfdX5nuoMBQqio4FpfpT4jkfFNf5gGEFOlGW3UTQR/8JyoVCEvZ4Wau3OsIouv1U3du9uWvaqHoxIeI9HvnTVinSzu9P4EjE=
    on_success: change
    on_failure: always
