language: php
services: mongodb
before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev --no-interaction
php:
  - 5.5
  - 5.4
script:
  - ./vendor/bin/phpunit -c app/ --coverage-text
  - ./vendor/bin/phpcs --standard=PSR1 --ignore='app/cache/*' --ignore='app/check.php' --ignore='app/SymfonyRequirements.php' --ignore='web/check.php' src/ app/ web/
  - ./vendor/bin/phpcs --standard=PSR2 --ignore='app/cache/*' --ignore='app/check.php' --ignore='app/SymfonyRequirements.php' --ignore='web/check.php' src/ app/ web/
  - ./vendor/bin/phpcs --standard=ENTB --ignore='app/cache/*' --ignore='app/check.php' --ignore='app/SymfonyRequirements.php' --ignore='web/check.php' src/ app/ web/
