graviton:
    image: graviton/graviton
composer:
    image: composer/composer
    volumes_from:
        - graviton
    command: install --ignore-platform-reqs
    restart: no
mongodb:
    image: mongo
fpm:
    image: gravityplatform/php-fpm:develop
    links:
        - mongodb:mongodb
    environment:
        MONGODB_DB: 'db'
        MONGODB_URI: 'mongodb://mongodb:27017'
    volumes_from:
        - graviton
nginx:
    image: nginx
    links:
        - fpm:fpm
    volumes:
        - .docker-config/nginx/defaults.conf:/etc/nginx/conf.d/default.conf
    ports:
        - 80:80
