graviton_analytics_homepage:
    path:     /
    methods: [GET]
    defaults: { _controller: GravitonAnalyticsBundle:Default:index }

graviton_analytics_service:
    path:     /{service}
    methods: [GET]
    requirements:
        service: "[A-Za-z0-9_-]+"
    defaults: { _controller: GravitonAnalyticsBundle:Default:service }

graviton_analytics_service_schema:
    path:     /schema/{service}
    methods: [GET]
    requirements:
        service: "[A-Za-z0-9_-]+"
    defaults: { _controller: GravitonAnalyticsBundle:Default:serviceSchema }
