services:
    graviton.analytics.defaut_controller:
        class: Graviton\AnalyticsBundle\Controller\DefaultController
        public: true
        arguments:
            - "@graviton.analytics.service_manager"

    graviton.analytics.analytics_manager:
        class: Graviton\AnalyticsBundle\Manager\AnalyticsManager
        arguments:
            - "@doctrine_mongodb.odm.default_document_manager"
            - "%graviton.mongodb.default.server.db%"

    graviton.analytics.service_manager:
        class: Graviton\AnalyticsBundle\Manager\ServiceManager
        arguments:
            - "@request_stack"
            - "@graviton.analytics.analytics_manager"
            - "@=service(parameter('graviton.cache.provider.service_id'))"
            - "@router"
            - "%kernel.root_dir%/.."
            - "%graviton.analytics.cache_time.metadata%"

    graviton.analytics.homepage_listener:
        class: Graviton\AnalyticsBundle\Listener\HomepageRenderListener
        arguments:
            - "@graviton.analytics.service_manager"
        tags:
            - { name: kernel.event_listener, event: homepage.render, method: onRender }
