services:
    graviton.analytics.analytics_manager:
        class: Graviton\AnalyticsBundle\Manager\AnalyticsManager
        arguments:
            documentManager: "@doctrine_mongodb.odm.default_document_manager"

    graviton.analytics.request_service_converter:
        class: Graviton\AnalyticsBundle\Request\ParamConverter\ServiceConverter
        arguments:
            requestStack: "@request_stack"
            analyticsManager: "@graviton.analytics.analytics_manager"
            cacheProvider: "@=service(parameter('graviton.cache.provider.service_id'))"
            router: "@router"
            definitionBaseDirectory: "%kernel.root_dir%/.."
        tags:
            -
              name: request.param_converter
              priority: -2
              converter: graviton.analytics.request_service_converter
