parameters:
    graviton.i18n.controller.language.class: Graviton\I18nBundle\Controller\LanguageController
    graviton.i18n.controller.translatable.class: Graviton\I18nBundle\Controller\TranslatableController
    graviton.i18n.model.language.class: Graviton\I18nBundle\Model\Language
    graviton.i18n.model.translatable.class: Graviton\I18nBundle\Model\Translatable
    graviton.i18n.repository.language.class: Doctrine\ODM\MongoDB\DocumentRepository
    graviton.i18n.repository.translatable.class: Doctrine\ODM\MongoDB\DocumentRepository
    graviton.i18n.repository.translatablelanguage.class: Doctrine\ODM\MongoDB\DocumentRepository
    graviton.i18n.listener.contentlanguageresponse.class: Graviton\I18nBundle\Listener\ContentLanguageResponseListener
    graviton.i18n.listener.i18nrqlparsinglistener.class: Graviton\I18nBundle\Listener\I18nRqlParsingListener
    graviton.i18n.loader.doctrineodm.class: Graviton\I18nBundle\Translation\Loader\DoctrineODMLoader
    graviton.i18n.utils.class: Graviton\I18nBundle\Service\I18nUtils
    graviton.i18n.cacheutils.class: Graviton\I18nBundle\Service\I18nCacheUtils
    graviton.i18n.command.createtranslationresources.class: Graviton\I18nBundle\Command\CreateTranslationResourcesCommand
    graviton.i18n.translator.class: Graviton\I18nBundle\Translator\Translator
    graviton.i18n.serializer.handler.translatable.class: Graviton\I18nBundle\Serializer\Handler\TranslatableHandler
