services:
    graviton.i18n.repository.language:
        class: "%graviton.i18n.repository.language.class%"
        factory: 'doctrine_mongodb.odm.default_document_manager:getRepository'
        public: true
        arguments:
          - "GravitonI18nBundle:Language"

    graviton.i18n.model.language:
        class: "%graviton.i18n.model.language.class%"
        parent: "graviton.rest.model"
        public: true
        calls:
          -
            method: "setRepository"
            arguments:
              - "@graviton.i18n.repository.language"

    graviton.i18n.controller.language:
        class: "%graviton.i18n.controller.language.class%"
        parent: "graviton.rest.controller"
        public: true
        calls:
        -
            method: "setModel"
            arguments:
            - "@graviton.i18n.model.language"
        tags:
        -
            name: "graviton.rest"

    graviton.i18n.listener.contentlanguageresponse:
        class: "%graviton.i18n.listener.contentlanguageresponse.class%"
        arguments:
            - "@graviton.18n.utils"
        tags:
          -
            name: "kernel.event_listener"
            event: "kernel.response"
            method: "onkernelresponse"

    graviton.i18n.translator:
        class: "%graviton.i18n.translator.class%"
        arguments:
            - "@doctrine_mongodb.odm.default_document_manager"
            - "%graviton.translator.default.locale%"

    graviton.i18n.listener.i18nrqlparsinglistener:
        class: "%graviton.i18n.listener.i18nrqlparsinglistener.class%"
        arguments:
          - "@graviton.18n.utils"
          - "%graviton.document.type.translatable.fields%"
        tags:
          -
            name: "kernel.event_listener"
            event: "rql.visit.node"
            method: "onvisitnode"

    # this here specifies the 'original' language --"
    graviton.18n.utils:
        class: "%graviton.i18n.utils.class%"
        arguments:
          - "@doctrine_mongodb.odm.default_document_manager"
          - "@graviton.i18n.translator"

    graviton.i18n.serializer.handler.translatable:
        class: "%graviton.i18n.serializer.handler.translatable.class%"
        public: true
        arguments:
        - "@graviton.18n.utils"
        tags:
        - name: "jms_serializer.handler"
          type: "Graviton\\DocumentBundle\\Entity\\Translatable"
          format: "json"
