Graviton\CoreBundle\Document\App:
  fields:
    id:
      type: string
      id: true
      strategy: UUID
    name:
      type: translatable
    showInMenu:
      type: boolean
    order:
      type: int
