imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

parameters:
    # build time parameters.. from from runtime to build time
    graviton.generator.dynamicbundle.dir: null
    graviton.generator.synthetic_fields: null
    graviton.generator.synthetic_fields_expose_on: null
    graviton.generator.ensure_indexes: null

    # end build time parameters

    secret: ThisTokenIsNotSoSecretChangeIt

    graviton.document.dateFormat: 'Y-m-d\TH:i:sO'
    graviton.document.timezone: UTC

    graviton.jmespath.cache_dir: '%kernel.cache_dir%/jmespath'

    graviton.security.services.whitelist: {  }

    graviton.translator.default.locale: en
    graviton.translator.cache_name_depth: 3

    graviton.router.host: null
    graviton.router.port_http: null
    graviton.router.port_https: null

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    graviton.rabbitmq.consumer.dump.routingkeys:
        - 'document.#'

    graviton.proxy.custom.sources: {  }
    graviton.proxy.redirect.sources: {  }

    graviton.writelock.randomwaiturls:
        - /event/status

    graviton.cache.provider.override: null
    graviton.cache.server.header: xkey

# Synfony Framework Configuation
# see http://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%secret%"
    php_errors:
        log: true
    router:
        resource: "%kernel.project_dir%/app/config/routing.yml"
        utf8: true
        strict_requirements: ~
    form:
        enabled: false
    csrf_protection: false
    validation:
        enabled:              true
        enable_annotations:   false
    default_locale: "%graviton.translator.default.locale%"
    trusted_hosts: ~
    fragments: ~

graviton_common:
    mongo_document_manager_service_id: doctrine_mongodb.odm.default_document_manager
    cache:
        instance_id: "%graviton.cache.instance_id%"
        redis_host: "%graviton.cache.redis.host%"
        redis_port: "%graviton.cache.redis.port%"
        adapter_override: null
    http_client:
        options:
            stream: false
            http_errors: false
            cookies: true
        verify_peer: "%graviton.core.httpclient.verifyPeer%"
        debug_requests: "%graviton.core.httpclient.debugRequests%"
        debug_max_length: "%graviton.core.httpclient.debugMaxLength%"
    deployment:
        check_package_name: "%graviton.core.checkPackageName%"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: null

# DoctrineMongoDB Configuration
# see: http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/config.html
doctrine_mongodb:
    default_database: "%mongodb.default.server.db%"
    proxy_dir: "%kernel.project_dir%/src/Doctrine/Proxies"
    hydrator_dir: "%kernel.project_dir%/src/Doctrine/Hydrators"
    connections:
        default:
            server: "%mongodb.default.server.uri%"
            options: {}
    document_managers:
        default:
            auto_mapping: true
            metadata_cache_driver:
                type: "service"
                id: "graviton.common.cache.adapter.app.doctrine"


# JmsSerializerBundle Configuration
# see: http://jmsyst.com/bundles/JMSSerializerBundle/master/configuration
jms_serializer:
    handlers:
        datetime:
            default_format: Y-m-d\TH:i:sO
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
        separator: ''
    default_context:
        serialization:
            serialize_null: false
    metadata:
        cache: graviton.core.jms.cache.provider
        debug: "%kernel.debug%"
        auto_detection: true

oneup_flysystem:
    adapters:
        local:
            local:
                location: "%graviton.file.local.storage_directory%"
        s3:
            async_aws_s3:
                client: graviton.file.asyncs3.client
                bucket: "%graviton.file.s3.bucket%"
                prefix: ''

    filesystems:
        graviton:
            #adapter: '%env(resolve:FILE_BACKEND)%'
            adapter: local

graviton_proxy:
    sources:
        swagger: "%graviton.proxy.swagger.sources%"
        custom: "%graviton.proxy.custom.sources%"
        redirect: "%graviton.proxy.redirect.sources%"

graviton_core:
    service_name:
        - graviton.core.static.version.get
        - graviton.security.static.whoami.get
    uri_whitelist:
        - /core/version
        - /person/whoami

sentry:
    dsn: "%graviton.sentry.dsn%"
    register_error_listener: false
    tracing:
        enabled: false
    options:
        # see https://github.com/getsentry/sentry-symfony/issues/421
        ## as we cannot filter here, we disable all and enable those that we want
        default_integrations: false
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'
            - 'Sentry\Integration\RequestIntegration'
            - 'Sentry\Integration\TransactionIntegration'
            - 'Sentry\Integration\FrameContextifierIntegration'
            - 'Sentry\Integration\EnvironmentIntegration'
            - 'Sentry\Integration\ModulesIntegration'
        environment: "%kernel.environment%"
