imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

parameters:

# Synfony Framework Configuation
# see http://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:
        enabled: false
    csrf_protection: false
    validation:
        enabled:              true
        enable_annotations:   false
    default_locale: "%locale%"
    trusted_hosts: ~
    session:
        name: graviton
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: null

# doctrine cache configuration
doctrine_cache:
    providers:
        local:
            php_file:
                directory: "%kernel.cache_dir%/doctrinecache_local"
        file:
            file_system:
                directory: "%kernel.cache_dir%/doctrinecache_files"
        array:
            array:
        redis:
            redis:
                database: 2
                host: "%graviton.cache.redis.host%"
                port: "%graviton.cache.redis.port%"

# DoctrineMongoDB Configuration
# see: http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/config.html
doctrine_mongodb:
    default_database: "%mongodb.default.server.db%"
    proxy_dir: "%kernel.project_dir%/src/Doctrine/Proxies"
    hydrator_dir: "%kernel.project_dir%/src/Doctrine/Hydrators"
    connections:
        default:
            server: "%mongodb.default.server.uri%"
            options: {}
        secondary:
            server: "%graviton.mongodb.default.server.uri_secondary%"
            options: {}
    document_managers:
        default:
            auto_mapping: true
            metadata_cache_driver:
                type: "service"
                id: "%graviton.cache.provider.service_id_local%"
        secondary:
            mappings: []
            metadata_cache_driver:
                type: "service"
                id: "%graviton.cache.provider.service_id_local%"


# JmsSerializerBundle Configuration
# see: http://jmsyst.com/bundles/JMSSerializerBundle/master/configuration
jms_serializer:
    handlers:
        datetime:
            default_format: Y-m-d\TH:i:sO
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
        separator: ''
    default_context:
        serialization:
            serialize_null: false
    metadata:
        cache: graviton.core.jms.cache.provider
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        auto_detection: true

oneup_flysystem:
    adapters:
        local:
            local:
                directory: "%graviton.file.local.storage_directory%"
        s3:
            awss3v3:
                client: graviton.file.s3.client
                bucket: "%graviton.file.s3.bucket%"
                prefix: ~
                options:
                    override_visibility_on_copy: private
    filesystems:
        graviton:
            adapter: '%graviton.file.backend%'

graviton_proxy:
    sources:
        swagger: "%graviton.proxy.swagger.sources%"
        custom: "%graviton.proxy.custom.sources%"
        redirect: "%graviton.proxy.redirect.sources%"

graviton_core:
    service_name:
        - graviton.core.static.version.get
        - graviton.security.static.whoami.get
    uri_whitelist:
        - /core/version
        - /person/whoami
