imports:
    - { resource: security_prod.yml }
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type: stream
            path: "%graviton.log.path%"
            level: "%graviton.log.level%"
            channels: [!event, !doctrine]
