imports:
    - { resource: security.yml }
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type: "stream"
            path: "php://stderr"
            level: "%graviton.log.level%"
            channels: ["!event"]
            formatter: "log_formatter"
