imports:
    - { resource: security.yml }
    - { resource: config.yml }

# sentry is active on prod
sentry:
    dsn: "%graviton.sentry.dsn%"
    skip_capture: "%graviton.sentry.dontReport%"
    options:
        environment: "%kernel.environment%"
        tags:
            application: graviton

monolog:
    handlers:
        main:
            type: "stream"
            path: "%graviton.log.path%"
            level: "%graviton.log.level%"
            channels: ["!event", "!doctrine", "!php"]
            formatter: "log_formatter"
