imports:
    - { resource: security.yml }
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type: "stream"
            path: "%graviton.log.path%"
            level: "%graviton.log.level%"
            channels: ["!event", "!doctrine", "!php"]
            formatter: "log_formatter"
        sentry:
            type: sentry
            level: !php/const Monolog\Logger::ERROR
            hub_id: Sentry\State\HubInterface
