graviton_rest_routing:
    resource: "@GravitonRestBundle/Resources/config/routing.xml"
    prefix: /

graviton_core_routing:
    resource: "@GravitonCoreBundle/Resources/config/routing.xml"
    prefix: /

graviton_swagger_routing:
    resource: "@GravitonSwaggerBundle/Resources/config/routing.xml"
    prefix: /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login