# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            #  no pattern means matches all routes
            stateless: true
            simple_preauth:
                authenticator: graviton_airlock_authentication_key_authenticator

    providers:
        graviton_airlock_authentication_key_user_provider:
            id: graviton_airlock_authentication_key_user_provider
