# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
    log_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.requestId%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"
            - "Y-m-d H:i:s.vP"
    test_consumer:
        class: Graviton\RabbitMqBundle\Consumer\TestConsumer

    # sentry
    Sentry\Integration\RequestIntegration:
    Sentry\Integration\TransactionIntegration:
    Sentry\Integration\FrameContextifierIntegration:
    Sentry\Integration\EnvironmentIntegration:
    Sentry\Integration\ModulesIntegration:
    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions: "%graviton.sentry.dontReport%"
