# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    test_consumer:
        class: Graviton\MessageBundle\Consumer\TestConsumer
    event_dispatcherr:
        class: Graviton\MessageBundle\Event\EventDispatcher
        arguments:
            - @service_container
        calls:
            - [setProducer, ["@old_sound_rabbit_mq.default_producer"]]

