Graviton\I18nBundle\Document\Translation:
  fields:
    id:
      id: true
      strategy: AUTO
    language:
      type: string
    original:
      type: string
    localized:
      type: string

  indexes:
    origIdx:
      keys:
        original: asc
      options:
        background: true
    origUniq:
      keys:
        original: asc
        language: asc
      options:
        background: true
        unique: true
