services:
    graviton.file.request_manager:
        class: "%graviton.file.request_manager.class%"
        arguments:
            - "@?request_stack"

    graviton.file.file_manager:
        class: "%graviton.file.file_manager.class%"
        arguments:
            - "@oneup_flysystem.graviton_filesystem"
            - "@doctrine_mongodb"
        calls:
          -
            method: setAllowedMimeTypes
            arguments:
              - "%graviton.file.allowed.mime_types%"
          -
            method: setReadFileSystemMimeType
            arguments:
              - "%graviton.file.read_filesystem_mimetype%"

    graviton.file.s3.client:
        class: Aws\S3\S3Client
        arguments:
            -
                endpoint: "%graviton.file.s3.endpoint%"
                bucket: "%graviton.file.s3.bucket%"
                version: "%graviton.file.s3.version%" # or 'latest'
                region: "%graviton.file.s3.region%" # 'eu-central-1' for example
                use_path_style_endpoint: true
                credentials:
                    key: "%graviton.file.s3.credentials.key%"
                    secret: "%graviton.file.s3.credentials.secret%"

    graviton.file.controller.file:
        class: "%graviton.file.controller.file.class%"
        public: true
        parent: "graviton.rest.controller"
        calls:
          -
            method: setModel
            arguments:
                -  "@?gravitondyn.file.model.file"
          -
            method: setFileManager
            arguments:
                - "@graviton.file.file_manager"
          -
            method: setRequestManager
            arguments:
                - "@graviton.file.request_manager"

