services:
    graviton.file.request_manager:
        class: "%graviton.file.request_manager.class%"
        arguments:
            - "@?request_stack"

    graviton.file.file_manager:
        class: "%graviton.file.file_manager.class%"
        arguments:
            - "@oneup_flysystem.graviton_filesystem"
            - "@doctrine_mongodb"
        calls:
          -
            method: setAllowedMimeTypes
            arguments:
              - "%graviton.file.allowed.mime_types%"

    graviton.file.controller.file:
        class: "%graviton.file.controller.file.class%"
        parent: "graviton.rest.controller"
        calls:
          -
            method: setModel
            arguments:
                -  "@?gravitondyn.file.model.file"
          -
            method: setFileManager
            arguments:
                - "@graviton.file.file_manager"
          -
            method: setRequestManager
            arguments:
                - "@graviton.file.request_manager"

