services:
    graviton_generator.resourcegenerator.field_mapper:
      class: "%graviton_generator.resourcegenerator.field_mapper.class%"
      calls:
        -
          method: addMapper
          arguments:
            - "@graviton_generator.resourcegenerator.field_type_mapper"
        -
          method: addMapper
          arguments:
            - "@graviton_generator.resourcegenerator.field_name_mapper"
        -
          method: addMapper
          arguments:
            - "@graviton_generator.resourcegenerator.field_json_mapper"
        -
          method: addMapper
          arguments:
            - "@graviton_generator.resourcegenerator.field_title_mapper"
        -
          method: addMapper
          arguments:
            - "@graviton_generator.resourcegenerator.field_hiddenrestriction_mapper"

    graviton_generator.resourcegenerator.field_type_mapper:
        class: "%graviton_generator.resourcegenerator.field_type_mapper.class%"

    graviton_generator.resourcegenerator.field_name_mapper:
        class: "%graviton_generator.resourcegenerator.field_name_mapper.class%"

    graviton_generator.resourcegenerator.field_json_mapper:
        class: "%graviton_generator.resourcegenerator.field_json_mapper.class%"

    graviton_generator.resourcegenerator.field_title_mapper:
        class: "%graviton_generator.resourcegenerator.field_title_mapper.class%"

    graviton_generator.resourcegenerator.field_hiddenrestriction_mapper:
        class: "%graviton_generator.resourcegenerator.field_hiddenrestriction_mapper.class%"

    graviton_generator.definition.loader:
        class: "%graviton_generator.definition.loader.class%"
        arguments:
            - "@graviton.jsonschema.validator"
            - "@jms_serializer"
        calls:
          -
            method: addStrategy
            arguments:
              - "@graviton_generator.definition.loader.strategy.file"
          -
            method: addStrategy
            arguments:
              - "@graviton_generator.definition.loader.strategy.dir"
          -
            method: addStrategy
            arguments:
              - "@graviton_generator.definition.loader.strategy.scan"
          -
            method: addStrategy
            arguments:
              - "@graviton_generator.definition.loader.strategy.json"

    graviton_generator.definition.loader.strategy.abstract:
        abstract: true

    graviton_generator.definition.loader.strategy.file:
        class: "%graviton_generator.definition.loader.strategy.file.class%"
        parent: "graviton_generator.definition.loader.strategy.abstract"

    graviton_generator.definition.loader.strategy.json:
        class: "%graviton_generator.definition.loader.strategy.json.class%"
        parent: "graviton_generator.definition.loader.strategy.abstract"

    graviton_generator.definition.loader.strategy.dir:
        class: "%graviton_generator.definition.loader.strategy.dir.class%"
        parent: "graviton_generator.definition.loader.strategy.abstract"

    graviton_generator.definition.loader.strategy.scan:
        class: "%graviton_generator.definition.loader.strategy.scan.class%"
        parent: "graviton_generator.definition.loader.strategy.abstract"
        calls:
          -
            method: setScanDir
            arguments:
              - "%kernel.project_dir%"

    graviton_generator.resourcegenerator.parameter_builder:
        class: "%graviton_generator.resourcegenerator.parameter_builder.class%"

    # generators

    ## abstract
    graviton_generator.generator.abstract:
        abstract: true
        calls:
          -
            method: setExposeSyntheticMap
            arguments:
              - "%graviton.generator.synthetic_fields_expose_on%"

    graviton_generator.generator.bundle:
        parent: graviton_generator.generator.abstract
        class: "%graviton_generator.generator.bundle.class%"

    graviton_generator.generator.resource:
        parent: graviton_generator.generator.abstract
        class: "%graviton_generator.generator.resource.class%"
        arguments:
          - "@filesystem"
          - "@graviton_generator.resourcegenerator.field_mapper"
          - "@graviton_generator.resourcegenerator.parameter_builder"

    graviton_generator.generator.dynamicbundlebundle:
        parent: graviton_generator.generator.abstract
        class: "%graviton_generator.generator.dynamicbundlebundle.class%"

    # commands

    graviton_generator.command.generatedynamicbundle:
        class: "Graviton\\GeneratorBundle\\Command\\GenerateDynamicBundleCommand"
        arguments:
          - "@graviton_generator.definition.loader"
          - "@graviton_generator.generator.bundle"
          - "@graviton_generator.generator.resource"
          - "@graviton_generator.generator.dynamicbundlebundle"
          - "@jms_serializer"
          - "%generator.bundlebundle.additions%"
          - "%generator.dynamicbundles.service.whitelist%"
          - null
          - "%graviton.generator.synthetic_fields%"
          - "%graviton.generator.ensure_indexes%"
        tags:
          -
            name: console.command

    graviton_generator.command.bundlebundleunload:
        class: "Graviton\\GeneratorBundle\\Command\\BundeBundleUnloadCommand"
        tags:
        -
            name: console.command

    graviton_generator.command.cachedocumentannotation:
      class: "Graviton\\GeneratorBundle\\Command\\CacheDocumentAnnotationCommand"
      tags:
        -
          name: console.command
