services:
    graviton.log.monolog.processor.requestId:
        class: "%graviton.log.monolog.processor.requestId.class%"
        tags:
            - { name: monolog.processor, method: processRecord }
