parameters:
  kernel.listener.graviton_exception_validation_exception.class: Graviton\ExceptionBundle\Listener\ValidationExceptionListener
  kernel.listener.graviton_exception_notfound_exception.class: Graviton\ExceptionBundle\Listener\NotFoundExceptionListener
  kernel.listener.graviton_exception_serialization_exception.class: Graviton\ExceptionBundle\Listener\SerializationExceptionListener
  kernel.listener.graviton_exception_deserialization_exception.class: Graviton\ExceptionBundle\Listener\DeserializationExceptionListener
  kernel.listener.graviton_exception_noinput_exception.class: Graviton\ExceptionBundle\Listener\NoInputExceptionListener
  kernel.listener.graviton_exception_rqlsyntaxerror.class: Graviton\ExceptionBundle\Listener\RqlSyntaxErrorListener
  kernel.listener.graviton_exception_rqloperatornotallowed.class: Graviton\ExceptionBundle\Listener\RqlOperatorNotAllowedListener
  kernel.listener.graviton_exception_malformedinput_exception.class: Graviton\ExceptionBundle\Listener\MalformedInputExceptionListener
  kernel.listener.graviton_exception_invalidjsonpatch_exception.class: Graviton\ExceptionBundle\Listener\InvalidJsonPatchExceptionListener
  kernel.listener.graviton_exception_recordoriginmodified_exception.class: Graviton\ExceptionBundle\Listener\RecordOriginExceptionListener

services:
    kernel.listener.graviton_exception_notfound_exception:
        class: "%kernel.listener.graviton_exception_notfound_exception.class%"
        tags:
          -
            name: kernel.event_listener
            event: kernel.exception
            method: onKernelException

    kernel.listener.graviton_exception_validation_exception:
        class: "%kernel.listener.graviton_exception_validation_exception.class%"
        calls:
          -
            method: setConstraintUtils
            arguments:
                - "@graviton.schema.constraint.utils"
        tags:
          -
            name: kernel.event_listener
            event: kernel.exception
            method: onKernelException

    kernel.listener.graviton_exception_serialization_exception:
        class: "%kernel.listener.graviton_exception_serialization_exception.class%"
        tags:
          -
            name: kernel.event_listener
            event: kernel.exception
            method: onKernelException

    kernel.listener.graviton_exception_deserialization_exception:
        class: "%kernel.listener.graviton_exception_deserialization_exception.class%"
        tags:
          -
            name: kernel.event_listener
            event: kernel.exception
            method: onKernelException

    kernel.listener.graviton_exception_noinput_exception:
        class: "%kernel.listener.graviton_exception_noinput_exception.class%"
        tags:
          -
            name: kernel.event_listener
            event: kernel.exception
            method: onKernelException

    kernel.listener.graviton_exception_rqlsyntaxerror:
        class: "%kernel.listener.graviton_exception_rqlsyntaxerror.class%"
        tags:
          -
            name: kernel.event_listener
            event: kernel.exception
            method: onKernelException

    kernel.listener.graviton_exception_rqloperatornotallowed:
        class: "%kernel.listener.graviton_exception_rqloperatornotallowed.class%"
        tags:
          -
            name: kernel.event_listener
            event: kernel.exception
            method: onKernelException

    kernel.listener.graviton_exception_malformedinput_exception:
        class: "%kernel.listener.graviton_exception_malformedinput_exception.class%"
        tags:
          -
            name: kernel.event_listener
            event: kernel.exception
            method: onKernelException

    kernel.listener.graviton_exception_invalidjsonpatch_exception:
        class: "%kernel.listener.graviton_exception_invalidjsonpatch_exception.class%"
        tags:
          -
            name: kernel.event_listener
            event: kernel.exception
            method: onKernelException

    kernel.listener.graviton_exception_recordoriginmodified_exception:
        class: "%kernel.listener.graviton_exception_recordoriginmodified_exception.class%"
        tags:
          -
            name: kernel.event_listener
            event: kernel.exception
            method: onKernelException
