parameters:
    graviton.document.service.extrefconverter.class: Graviton\DocumentBundle\Service\ExtReferenceConverter
    graviton.document.service.dateconverter.class: Graviton\DocumentBundle\Service\DateConverter
    graviton.document.service.collectioncache.class: Graviton\DocumentBundle\Service\CollectionCache
    graviton.document.service.solrquery.class: Graviton\DocumentBundle\Service\SolrQuery
    graviton.document.service.solrquery.client.class: Solarium\Client
    graviton.document.service.solrquery.client.adapter.class: Solarium\Core\Client\Adapter\Curl
    graviton.document.listener.extreferencesearchlistener.class: Graviton\DocumentBundle\Listener\ExtReferenceSearchListener
    graviton.document.listener.rqlsearch.class: Graviton\DocumentBundle\Listener\RqlSearchNodeListener
    graviton.document.listener.fieldnamesearchlistener.class: Graviton\DocumentBundle\Listener\FieldNameSearchListener
    graviton.document.listener.documentversionlistener.class: Graviton\DocumentBundle\Listener\DocumentVersionListener
    graviton.document.serializer.handler.hash.class: Graviton\DocumentBundle\Serializer\Handler\HashHandler
    graviton.document.serializer.handler.extref.class: Graviton\DocumentBundle\Serializer\Handler\ExtReferenceHandler
    graviton.document.serializer.handler.date.class: Graviton\DocumentBundle\Serializer\Handler\DateHandler
    graviton.document.serializer.visitor.jsonserialization.class: Graviton\DocumentBundle\Serializer\Visitor\JsonSerializationVisitorFactory
    graviton.document.serializer.visitor.jsondeserialization.class: Graviton\DocumentBundle\Serializer\Visitor\JsonDeserializationVisitorFactory
    graviton.document.serializer.subscriber.doctrineproxy.class: Graviton\DocumentBundle\Serializer\Subscriber\DoctrineProxySubscriber
