services:
    graviton.document.service.extrefconverter:
        class: "%graviton.document.service.extrefconverter.class%"
        public: true
        arguments:
            - "@router"
            - "%graviton.document.type.extref.mapping%"

    graviton.document.serializer.listener.emptyextref:
        class: "%graviton.document.serializer.listener.emptyextref.class%"
        tags:
          -
            name: jms_serializer.event_listener
            event: serializer.pre_serialize
            method: onPreSerialize
            direction: serialization

    graviton.document.listener.documentversion:
        class: "%graviton.document.listener.documentversionlistener.class%"
        arguments:
            - "@doctrine_mongodb.odm.default_document_manager"
            - "@graviton.schema.constraint.versionservice"
        tags:
          -
            name: kernel.event_listener
            event: document.model.event.insert
            method: modelInsert
          -
            name: kernel.event_listener
            event: document.model.event.update
            method: modelUpdate

    graviton.document.serializer.handler.empty:
        class: "%graviton.document.serializer.handler.empty.class%"
        tags:
          -
            name: jms_serializer.handler
            type: Empty
            format: json

    graviton.document.listener.extreferencesearchlistener:
        class: "%graviton.document.listener.extreferencesearchlistener.class%"
        arguments:
            - "@graviton.document.service.extrefconverter"
            - "%graviton.document.extref.fields%"
            - "@request_stack"
        tags:
          -
            name: kernel.event_listener
            event: rql.visit.node
            method: onVisitNode
            priority: 2

    graviton.document.listener.fieldnamesearchlistener:
        class: "%graviton.document.listener.fieldnamesearchlistener.class%"
        arguments:
            - "%graviton.document.rql.fields%"
            - "@request_stack"
        tags:
          -
            name: kernel.event_listener
            event: rql.visit.node
            method: onVisitNode
            priority: 1

    graviton.document.serializer.handler.hash:
        class: "%graviton.document.serializer.handler.hash.class%"
        arguments:
            - "@request_stack"
        tags:
          -
            name: jms_serializer.handler
            type: Graviton\DocumentBundle\Entity\Hash
            format: json

    graviton.document.serializer.handler.extref:
        class: "%graviton.document.serializer.handler.extref.class%"
        arguments:
            - "@graviton.document.service.extrefconverter"
        tags:
          -
            name: jms_serializer.handler
            type: Graviton\DocumentBundle\Entity\ExtReference
            format: json
          -
            name: kernel.event_listener
            event: graviton.json_schema.constraint.format
            method: validateExtRef

    graviton.document.serializer.handler.date:
        class: "%graviton.document.serializer.handler.date.class%"
        tags:
          -
            name: jms_serializer.subscribing_handler
            type: DateTime
            format: json
