name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    name: PHP 8.1

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    services:
      mongodb:
        image: mongo:5.0

    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Docker Layer Caching
        # You may pin to the exact commit or the version.
        # uses: satackey/action-docker-layer-caching@46d2c640b1d8ef50d185452ad6fb324e6bd1d052
        uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: graviton-php81-{hash}
          restore-keys: |
            graviton-php81-

      - name: Run composer and tests (with coverage)
        uses: ./.github/actions/test-php81
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Junit Report to Annotations
        # You may pin to the exact commit or the version.
        # uses: ashley-taylor/junit-report-annotations-action@562e0277515cae408f30ad1ea2d6dea44fc1df87
        uses: ashley-taylor/junit-report-annotations-action@1.3
        with:
          # github token
          access-token: ${{ secrets.GITHUB_TOKEN }}
          # glob to junit xml files
          path: phpunit_junit.xml
