name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    name: PHP 7.4

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    services:
      mongodb:
        image: mongo:4.4

    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Docker Layer Caching
        # You may pin to the exact commit or the version.
        # uses: satackey/action-docker-layer-caching@46d2c640b1d8ef50d185452ad6fb324e6bd1d052
        uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Run composer and tests
        uses: ./.github/actions/test-php74

  build8:

    name: PHP 8.0

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    services:
      mongodb:
        image: mongo:4.4

    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: PHPUnit cache
        id: phpunit-cache
        uses: actions/cache@v2
        with:
          path: var/cache/phpunit
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Docker Layer Caching
        # You may pin to the exact commit or the version.
        # uses: satackey/action-docker-layer-caching@46d2c640b1d8ef50d185452ad6fb324e6bd1d052
        uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Run composer and tests
        uses: ./.github/actions/test-php80
