name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    name: PHP 7.4

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    services:
      mongodb:
        image: mongo:4.4

    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Run composer and tests
        uses: ./.github/actions/test-php74

  build8:

    name: PHP 8.0

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    services:
      mongodb:
        image: mongo:4.4

    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Run composer and tests
        uses: ./.github/actions/test-php80
